sudo: required
services:
  - docker

before_install:
  - docker build -t rtapanine/docker-react-test -f Dockerfile.dev .

script:
  - docker run rtapanine/docker-react-test npm run test -- --coverage
